# Generated by Django 4.1.5 on 2023-04-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_whey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whey',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Marka'),
        ),
    ]
