# Generated by Django 4.1.5 on 2023-04-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_alter_whey_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Marka')),
                ('img', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('text', models.TextField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
    ]
