# Generated by Django 4.1.5 on 2023-04-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_rename_soya_zcasein_rename_casein_zsoya_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZAksesuar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Marka')),
                ('img', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('text', models.TextField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='ZAminoAsit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Marka')),
                ('img', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('text', models.TextField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='ZBcaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Marka')),
                ('img', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('text', models.TextField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='ZCreatin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Marka')),
                ('img', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('text', models.TextField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='ZKafein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Marka')),
                ('img', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('text', models.TextField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='ZLCarnitine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Marka')),
                ('img', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('text', models.TextField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='ZVitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Marka')),
                ('img', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('text', models.TextField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
    ]
