# Generated by Django 4.1.5 on 2023-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_zyagyakım_zaksesuar_price_alter_zaksesuar_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zyagyakım',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
    ]
