# Generated by Django 4.1.5 on 2023-04-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_zfull_zguc_zgun_zhıt_zilerı_zmakro_znasıl_zppl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zguc',
            name='list',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Liste'),
        ),
    ]
