# Generated by Django 4.1.5 on 2023-04-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0014_alter_zguc_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaksesuar',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug Title'),
        ),
    ]
