# Generated by Django 4.1.5 on 2023-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0016_alter_zaksesuar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvitamin',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug Title'),
        ),
    ]
