# Generated by Django 4.1.5 on 2023-04-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0017_zvitamin_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstok',
            name='price',
            field=models.FloatField(null=True, verbose_name='Ortalama Fiyat'),
        ),
    ]
