# Generated by Django 4.1.5 on 2023-04-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0018_productstok_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaminoasit',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug Title'),
        ),
        migrations.AddField(
            model_name='zbcaa',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug Title'),
        ),
        migrations.AddField(
            model_name='zcasein',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug Title'),
        ),
        migrations.AddField(
            model_name='zcreatin',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug Title'),
        ),
        migrations.AddField(
            model_name='zkafein',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug Title'),
        ),
        migrations.AddField(
            model_name='zlcarnitine',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug Title'),
        ),
        migrations.AddField(
            model_name='zsoya',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug Title'),
        ),
        migrations.AddField(
            model_name='zwhey',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug Title'),
        ),
    ]
