# Generated by Django 4.1.5 on 2023-04-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0019_zaminoasit_slug_zbcaa_slug_zcasein_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zwhey',
            name='list',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Liste'),
        ),
    ]
