# Generated by Django 4.1.5 on 2023-04-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0021_zbcaa_list_zcasein_list_zcreatin_list_zsoya_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='zfull',
            name='list',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Liste'),
        ),
        migrations.AddField(
            model_name='zgun',
            name='list',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Liste'),
        ),
        migrations.AddField(
            model_name='zilerı',
            name='list',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Liste'),
        ),
        migrations.AddField(
            model_name='zmakro',
            name='list',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Liste'),
        ),
        migrations.AddField(
            model_name='znasıl',
            name='list',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Liste'),
        ),
        migrations.AddField(
            model_name='zppl',
            name='list',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Liste'),
        ),
        migrations.AddField(
            model_name='zsecım',
            name='list',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Liste'),
        ),
    ]
