# Generated by Django 4.1.5 on 2023-04-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0023_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
