# Generated by Django 4.1.5 on 2023-04-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0025_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
