# Generated by Django 4.1.5 on 2023-04-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0029_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
