# Generated by Django 4.1.5 on 2023-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0033_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zsoya',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Açıklama'),
        ),
    ]
