# Generated by Django 4.1.5 on 2023-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0035_alter_zbcaa_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaksesuar',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='zaminoasit',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='zcreatin',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='zkafein',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='zlcarnitine',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='zvitamin',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Açıklama'),
        ),
    ]
